# Generated by Django 5.2.6 on 2025-09-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='name',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(),
        ),
    ]
